#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     IRSeeker,       sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorTL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorTR,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorBrush,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoGrip1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoGrip2,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int tickGoal = (1146 * 24) / 10;
int tickTest = nMotorEncoder[motorBR];

void driveDistance(int inches)
{
	//Reset encoder
	tickTest = 0;

	//Encoders have 1440 ticks per revolution of the wheel
	//Encoder ticks = (1440/circumference) * Distance to travel
	//Wheel diameter = 4 inches
	//Wheel circumference = 12.57 inches
	//1440 / 12.57 = 114.6 ticks per inch
	//Round 114.6 ticks per inch to 1146 ticks per 10 inches
	//int tickGoal = (1146 * 24) / 10;

	while(tickTest < tickGoal)
	{
		motor[motorTR] = 30;
		motor[motorTL] = 30;
		motor[motorBR] = 30;
		motor[motorBL] = 30;

		tickTest = nMotorEncoder[motorBR];
		wait1Msec(500);
	}

	motor[motorTR] = 0;
	motor[motorTL] = 0;
	motor[motorBR] = 0;
	motor[motorBL] = 0;
}

task main()
{
	tickTest = 0;
	driveDistance(2);
	motor[motorTR] = 0;
	motor[motorTL] = 0;
	motor[motorBR] = 0;
	motor[motorBL] = 0;

	while(true){
		tickTest = nMotorEncoder[motorBR];
	}
}
