#pragma config(Sensor, S2,     ,               sensorDigitalIn)
#pragma config(Sensor, S4,     IRSensor,       sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\viperbots\Documents\GitHub\FTC7161\drivers\hitechnic-irseeker-v2."

int value = SensorValue[IRSensor];


task main()
{
//	while(true)
//	{
//		if(SensorValue[IRSensor] == 0)
//		{
//			motor[motorTR] = 30;
//		}
//		else
//		{
//			motor[motorBL] = 30;
//		}
//}
while(true)
	{
		nxtDisplayString(1, "%d", value);
		value = SensorValue[IRSensor];
	}
}
