#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorTR,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorTL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorBrush,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorConveyor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "C:\Users\viperbots\Documents\GitHub\FTC7161\drivers\hitechnic-irseeker-v2."



task main()
{
	while(true)  // infinite loop:
	{
	  nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[IRSensor]);  // display "Sensor Value: ##"
	  wait1Msec(50);  // Wait 100 milliseconds to help display correctly

	  while(SensorValue[IRSensor] == 0)
	  {
		  motor[motorTR] = 10;
		  motor[motorTL] = 10;
		  motor[motorBR] = 10;
		  motor[motorBL] = 10;
		}

		motor[motorTR] = 0;
		motor[motorTL] = 0;
		motor[motorBR] = 0;
		motor[motorBL] = 0;

	}
}
