#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     IRSeeker,       sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorTL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorTR,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motor,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorBrush,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoGrip1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoGrip2,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int testOne = nMotorEncoder[motorTR];
int testTwo = nMotorEncoder[motorTL];
int testThree = nMotorEncoder[motorBR];
int testFour = nMotorEncoder[motorBL];

task main()
{
	motor[motorTL] = 20;
	motor[motorBL] = 20;
	motor[motorTR] = 20;
	motor[motorBR] = 20;

	wait1Msec(3000);

	motor[motorTL] = 0;
	motor[motorBL] = 0;
	motor[motorTR] = 0;
	motor[motorBR] = 0;

	//testOne = 0;

	//while(testOne < 300)
	//{
	//	motor[motorTL] = 20;
	//	motor[motorBL] = 20;
	//	motor[motorTR] = 20;
	//	motor[motorBR] = 20;
	//}

	//motor[motorTL] = 0;
	//motor[motorBL] = 0;
	//motor[motorTR] = 0;
	//motor[motorBR] = 0;

	while(true)
	{
		 testOne = nMotorEncoder[motorTR];
 testTwo = nMotorEncoder[motorTL];
 testThree = nMotorEncoder[motorBR];
 testFour = nMotorEncoder[motorBL];
}



}
