#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	servo[servoHingeL] = 170;
	servo[servoHingeR] = 75;
	wait10Msec(250);
	servo[servoHingeL] = 0;
	servo[servoHingeR] = 255;
}
