#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorTL,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorTR,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorBrush,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorConveyor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorPulley,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servoBasket,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//task IR ()
//{
//	while(true)
//	{
//		if (SensorValue[IRSeeker] == 5)
//		{
//			motor[motorTL] = 0;
//			motor[motorTR] = 0;
//			motor[motorBL] = 0;
//			motor[motorBR] = 0;
//		}
//	}
//}

//joystick 1 control

task drive()  	//tank drive
{
	while (true)
  {
		if(abs(joystick.joy1_y1) > 25)
		{
			motor[motorTL] = joystick.joy1_y1 ;
			motor[motorBL] = joystick.joy1_y1 ;
		}

		else
		{
			motor[motorTL] = 0;
	    motor[motorBL] = 0;
	   }

	   if(abs(joystick.joy1_y2) > 25)
	   {
	    motor[motorTR] = joystick.joy1_y2 ;
			motor[motorBR] = joystick.joy1_y2 ;
		}

			else
		{
	    motor[motorTR] = 0;
	    motor[motorBR] = 0;
	   }
	}
}

task baseGrip()	//method for grippers
{
	while(true)
	{
		//reset servos to upright position
		servo[servoHingeR] = 85;
		servo[servoHingeL] = 170;
		//switches hinges between up and down positions
		if (joy1Btn(3) == 1)
		{
			if (servo[servoHingeR] == 255)
		  {
		  	//move to upright position
		  	servo[servoHingeR] = 85;
				servo[servoHingeL] = 170;
				wait1Msec(500);
			}
			else
			{
				//move to down position
				servo[servoHingeR] = 255;
				servo[servoHingeL] = 0;
				wait1Msec(500);
			}
		}
		wait1Msec(5);

	}
}

//joystick 2 control

//task brushConveyor()	//method for base brush and conveyor complex
//{
//	while(true)
//	{
//		//move brush and conveyor forward or backward with joystick values
//		if(abs(joystick.joy2_y1) > 10)
//		{
//			motor[motorBrush] = joystick.joy2_y1;
//			motor[motorConveyor] = joystick.joy2_y1;
//		}
//		else
//		{
//			motor[motorBrush] = 0;
//			motor[motorConveyor] = 0;
//		}
//		wait1Msec(5);
//	}
//}


//task pulley() //method for pulley system
//{
//	while(true)
//	{
//		if(abs(joystick.joy2_y2) > 10)
//		{
//			motor[motorPulley] = joystick.joy2_y2;
//		}
//		else
//		{
//			motor[motorPulley] = 0;
//		}
//	}
//}

//task basket()
//{
//	while(true)
//	{
//		if(joy2Btn(5) == 1)
//		{
//			servo[servoBasket] = 180;
//		}
//		if(joy2Btn(6) == 1)
//		{
//			servo[servoBasket] = 0;
//		}
//	}
//}
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase
while(true)
{
  startTask(baseGrip);
 // startTask(brushConveyor);
	startTask(drive);
//	startTask(pulley);
//	startTask(basket);
}
}
