#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     motorTR,       tmotorTetrix, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorTL,       tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorPulley,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorb,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motora,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorBrush,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servoBasket,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servoBlocker,         tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

/* CONTROLS
CONTROLLER 1
	* Y button
	* X button
	* A button
	* B button
	* Left Analog Y- tankdrive
	* Right Analog Y- tankdrive
	* Left Analog X
	* Right Analog X

CONTROLLER 2
	* Y button
	* X Button
	* A button
	* B button
	* Left Analog Y- brush
	* Right Analog Y- pulley
	* Left Analog X
	* Right Analog X
*/

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//joystick 1 control

task drive()  	//tank drive
{
	while (true)
  {
		if(abs(joystick.joy1_y1) > 25) //If joystick greater than 25 in either direction
		{
			motor[motorTL] = joystick.joy1_y1 ; //Power the left wheels that amount
			motor[motorBL] = joystick.joy1_y1 ;
		}

		else
		{
			motor[motorTL] = 0;
			motor[motorBL] = 0;
		}

		if(abs(joystick.joy1_y2) > 25)
		{
			motor[motorTR] = joystick.joy1_y2 ;
			motor[motorBR] = joystick.joy1_y2 ;
		}

		else
		{
			motor[motorTR] = 0;
			motor[motorBR] = 0;
		}
	}
}

task baseGrip()	//method for grippers
{
	//reset servos to upright position
	servo[servoHingeR] = 120;
	servo[servoHingeL] = 120;
	bool down = true;
	while(true)
	{

		//switches hinges between up and down positions
		if (joy1Btn(3) == 1) //If Button () pushed
		{
			if (!down) //If the servo is down
			{
		  	//move to upright position
				servo[servoHingeR] = 120;
				servo[servoHingeL] = 120;
				down = true;
				wait1Msec(500);
			}
			else //If the servo is up
			{
				//move to down position
				servo[servoHingeR] = 250;
				servo[servoHingeL] = 0;
				wait1Msec(500);
				down = false;
			}
		}
		wait1Msec(5); //latency
	}
}

//joystick 2 control

//task brushConveyor()	//method for base brush and conveyor complex
//{
//	while(true)
//	{
//		//move brush and conveyor forward or backward with joystick values
//		if(abs(joystick.joy2_y1) > 10)
//		{
//			motor[motorBrush] = joystick.joy2_y1;
//			motor[motorConveyor] = joystick.joy2_y1;
//		}
//		else
//		{
//			motor[motorBrush] = 0;
//			motor[motorConveyor] = 0;
//		}
//		wait1Msec(5);
//	}
//}


task pulley() //method for pulley system
{
	while(true)
	{
		if(abs(joystick.joy2_y2) > 10)
		{
			motor[motorPulley] = joystick.joy2_y2;
		}
		else
		{
			motor[motorPulley] = 0;
		}
	}
}

//Spins sponge brushes to collect balls
task brushWheels()
{
	while(true)
	{
		if(abs(joystick.joy2_y1) > 10)
		{
			motor[motorBrush] = joystick.joy2_y1;
		}
		else
		{
			motor[motorBrush] = 0;
		}
	}
}

task basket()
{
	while(true)
	{
		if (joy2Btn(5) == 1)
		{
			if (servo[servoBasket] > 100)
			{
				servo[servoBasket] = 70;
				wait1Msec(250);
			}
			else
			{
				servo[servoBasket] = 255;
				wait1Msec(250);
			}
		}
	}
}

task blocker()
{
	servo[servoBlocker] = 0;

	while(true)
	{
		if(joy2Btn(6) == 1) //toggle on/off of basket
			{
				if (servo[servoBlocker] == 255)
				{
					servo[servoBlocker] = 0;
					wait1Msec(250);
				}
				else if(servo[servoBlocker] == 0)
				{
					servo[servoBlocker] = 255;
					wait1Msec(250);
				}
			}
		//		servo[servoBlocker] = 0;
		//		wait1Msec(250);
		//	}
		//if (joy2Btn(2) == 1)
		//	{
		//		servo[servoBlocker] = 255;
		//		wait1Msec(250);
		//	}
		}
	}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servo[servoBasket] = 255; //Basket servo up

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  startTask(baseGrip);
	//startTask(brushConveyor);
	startTask(drive);
	startTask(pulley);
	startTask(basket);
	startTask(brushWheels);
	startTask(blocker);


	while(true)
	{
		getJoystickSettings(joystick);
	}
}
